package forms;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zahra AP
 */
public class BookList extends javax.swing.JFrame {

    /**
     * Creates new form BookList
     */
    public BookList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBookList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookList = new javax.swing.JTable();
        jSearch = new javax.swing.JLabel();
        jSearchField = new javax.swing.JTextField();
        jChoose = new javax.swing.JButton();
        jRule = new javax.swing.JLabel();
        jLogoutBookList = new javax.swing.JLabel();
        jExitBookList1 = new javax.swing.JLabel();
        jBookSelected = new javax.swing.JScrollPane();
        BookSelected = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book List");
        setLocation(new java.awt.Point(300, 300));
        setUndecorated(true);
        setResizable(false);

        jPanelBookList.setBackground(new java.awt.Color(102, 0, 102));
        jPanelBookList.setPreferredSize(new java.awt.Dimension(450, 600));

        BookList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null,  new Boolean(false)},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book", "Author", "Genre", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BookList.setColumnSelectionAllowed(true);
        BookList.setGridColor(new java.awt.Color(102, 0, 102));
        BookList.setSelectionBackground(new java.awt.Color(102, 0, 102));
        BookList.getTableHeader().setReorderingAllowed(false);
        BookList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                BookListPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(BookList);
        BookList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (BookList.getColumnModel().getColumnCount() > 0) {
            BookList.getColumnModel().getColumn(0).setResizable(false);
            BookList.getColumnModel().getColumn(1).setResizable(false);
            BookList.getColumnModel().getColumn(2).setResizable(false);
        }
        BookList.getAccessibleContext().setAccessibleName("");

        jSearch.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jSearch.setForeground(new java.awt.Color(255, 255, 255));
        jSearch.setText("Search");
        jSearch.setToolTipText("");

        jSearchField.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jSearchField.setMinimumSize(new java.awt.Dimension(6, 20));
        jSearchField.setSelectionColor(new java.awt.Color(102, 0, 102));
        jSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchFieldActionPerformed(evt);
            }
        });

        jChoose.setBackground(new java.awt.Color(255, 255, 255));
        jChoose.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jChoose.setForeground(new java.awt.Color(102, 0, 102));
        jChoose.setText("Choose");
        jChoose.setBorderPainted(false);
        jChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChooseActionPerformed(evt);
            }
        });

        jRule.setForeground(new java.awt.Color(255, 255, 255));
        jRule.setText("You can lend only one book at a time");

        jLogoutBookList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/interface-logout-4e8igal4j6tyuw6x0r6n5.png"))); // NOI18N
        jLogoutBookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutBookListMouseClicked(evt);
            }
        });

        jExitBookList1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/interface-delete-1-x8zqpdddl47ewg5ugtkv2.png"))); // NOI18N
        jExitBookList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitBookList1MouseClicked(evt);
            }
        });

        BookSelected.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Your Selected Book", "Get Date", "Give Back Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BookSelected.setColumnSelectionAllowed(true);
        BookSelected.setGridColor(new java.awt.Color(102, 0, 102));
        BookSelected.setSelectionBackground(new java.awt.Color(102, 0, 102));
        BookSelected.getTableHeader().setReorderingAllowed(false);
        jBookSelected.setViewportView(BookSelected);
        BookSelected.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (BookSelected.getColumnModel().getColumnCount() > 0) {
            BookSelected.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanelBookListLayout = new javax.swing.GroupLayout(jPanelBookList);
        jPanelBookList.setLayout(jPanelBookListLayout);
        jPanelBookListLayout.setHorizontalGroup(
            jPanelBookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBookListLayout.createSequentialGroup()
                        .addGroup(jPanelBookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRule)
                            .addComponent(jChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBookListLayout.createSequentialGroup()
                        .addComponent(jLogoutBookList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jExitBookList1)
                        .addContainerGap())
                    .addGroup(jPanelBookListLayout.createSequentialGroup()
                        .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSearch)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelBookListLayout.createSequentialGroup()
                        .addGroup(jPanelBookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBookSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        jPanelBookListLayout.setVerticalGroup(
            jPanelBookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBookListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jExitBookList1)
                    .addComponent(jLogoutBookList))
                .addGap(57, 57, 57)
                .addGroup(jPanelBookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRule, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChoose)
                .addGap(61, 61, 61)
                .addComponent(jBookSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBookList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBookList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChooseActionPerformed

    private void jSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchFieldActionPerformed

    private void jExitBookList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitBookList1MouseClicked
        dispose();
        System.exit (0);
    }//GEN-LAST:event_jExitBookList1MouseClicked

    private void jLogoutBookListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutBookListMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLogoutBookListMouseClicked

    private void BookListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_BookListPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_BookListPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookList;
    private javax.swing.JTable BookSelected;
    private javax.swing.JScrollPane jBookSelected;
    private javax.swing.JButton jChoose;
    private javax.swing.JLabel jExitBookList1;
    private javax.swing.JLabel jLogoutBookList;
    private javax.swing.JPanel jPanelBookList;
    private javax.swing.JLabel jRule;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSearch;
    private javax.swing.JTextField jSearchField;
    // End of variables declaration//GEN-END:variables
}
