package forms;

import classes.Customer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zahra AP
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jUsernameLogin = new javax.swing.JLabel();
        jPasswordLogin = new javax.swing.JLabel();
        jUsernameEnterLogin = new javax.swing.JTextField();
        jPasswordEnterLogin = new javax.swing.JPasswordField();
        jEnter = new javax.swing.JButton();
        jForget = new javax.swing.JLabel();
        jBackLogin = new javax.swing.JLabel();
        jExitLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setLocation(new java.awt.Point(300, 300));
        setUndecorated(true);
        setResizable(false);

        jPanelLogin.setBackground(new java.awt.Color(102, 0, 102));

        jUsernameLogin.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jUsernameLogin.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameLogin.setText("Username");
        jUsernameLogin.setToolTipText("");

        jPasswordLogin.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPasswordLogin.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordLogin.setText("Password");
        jPasswordLogin.setToolTipText("");

        jUsernameEnterLogin.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jUsernameEnterLogin.setSelectionColor(new java.awt.Color(102, 0, 102));

        jPasswordEnterLogin.setPreferredSize(new java.awt.Dimension(6, 36));
        jPasswordEnterLogin.setSelectionColor(new java.awt.Color(102, 0, 102));

        jEnter.setBackground(new java.awt.Color(255, 255, 255));
        jEnter.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jEnter.setForeground(new java.awt.Color(102, 0, 102));
        jEnter.setText("Enter");
        jEnter.setBorderPainted(false);
        jEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnterActionPerformed(evt);
            }
        });

        jForget.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jForget.setText("Forget Password");

        jBackLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/interface-arrows-turn-backward-3qynn3z1e3rizbfnn8xln.png"))); // NOI18N
        jBackLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackLoginMouseClicked(evt);
            }
        });

        jExitLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/interface-delete-1-x8zqpdddl47ewg5ugtkv2.png"))); // NOI18N
        jExitLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addComponent(jBackLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jExitLogin)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                        .addGap(0, 59, Short.MAX_VALUE)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                                .addComponent(jUsernameLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jUsernameEnterLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                                .addComponent(jEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                                .addComponent(jPasswordLogin)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordEnterLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                                .addComponent(jForget)
                                .addGap(174, 174, 174))))))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBackLogin)
                    .addComponent(jExitLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameLogin)
                    .addComponent(jUsernameEnterLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordEnterLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordLogin))
                .addGap(35, 35, 35)
                .addComponent(jEnter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jForget)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jjPanellogintionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginActionPerformed

    private void jEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnterActionPerformed
        
        String username = jUsernameEnterLogin.getText();
        String password = jPasswordEnterLogin.getText();
        Customer j = new Customer(username, password);
        
        if (username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your username and password to login");
        }
        else if (username.equals("admin") && password.equals("admin")) {
            new AdminPage().setVisible(true);
            this.dispose();
        }
        else {
//            j.checkUserPass();

            new BookList().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jEnterActionPerformed

    private void jExitLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitLoginMouseClicked
        dispose();
        System.exit (0);
    }//GEN-LAST:event_jExitLoginMouseClicked

    private void jBackLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackLoginMouseClicked
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBackLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackLogin;
    private javax.swing.JButton jEnter;
    private javax.swing.JLabel jExitLogin;
    private javax.swing.JLabel jForget;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordEnterLogin;
    private javax.swing.JLabel jPasswordLogin;
    private javax.swing.JTextField jUsernameEnterLogin;
    private javax.swing.JLabel jUsernameLogin;
    // End of variables declaration//GEN-END:variables
}
