package forms;

import classes.Customer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zahra AP
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegister = new javax.swing.JPanel();
        jNameRegister = new javax.swing.JLabel();
        jNameEnterRegister = new javax.swing.JTextField();
        jEmailRegister = new javax.swing.JLabel();
        jEmailEnterRegister = new javax.swing.JTextField();
        jNumberRegister = new javax.swing.JLabel();
        jNumberEnterRegister = new javax.swing.JTextField();
        jUsernameEnterRegister = new javax.swing.JTextField();
        jUsernameRegister = new javax.swing.JLabel();
        jPasswordRegister = new javax.swing.JLabel();
        jPasswordEnterRegister = new javax.swing.JPasswordField();
        jSubmit = new javax.swing.JButton();
        jBackRegister = new javax.swing.JLabel();
        jExitRegister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setLocation(new java.awt.Point(300, 300));
        setUndecorated(true);
        setResizable(false);

        jPanelRegister.setBackground(new java.awt.Color(102, 0, 102));

        jNameRegister.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jNameRegister.setForeground(new java.awt.Color(255, 255, 255));
        jNameRegister.setText("Name");
        jNameRegister.setToolTipText("");

        jNameEnterRegister.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jNameEnterRegister.setSelectionColor(new java.awt.Color(102, 0, 102));
        jNameEnterRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameEnterRegisterActionPerformed(evt);
            }
        });

        jEmailRegister.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jEmailRegister.setForeground(new java.awt.Color(255, 255, 255));
        jEmailRegister.setText("Email");
        jEmailRegister.setToolTipText("");

        jEmailEnterRegister.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jEmailEnterRegister.setSelectionColor(new java.awt.Color(102, 0, 102));
        jEmailEnterRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailEnterRegisterActionPerformed(evt);
            }
        });

        jNumberRegister.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jNumberRegister.setForeground(new java.awt.Color(255, 255, 255));
        jNumberRegister.setText("Number");
        jNumberRegister.setToolTipText("");

        jNumberEnterRegister.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jNumberEnterRegister.setSelectionColor(new java.awt.Color(102, 0, 102));
        jNumberEnterRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumberEnterRegisterActionPerformed(evt);
            }
        });

        jUsernameEnterRegister.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jUsernameEnterRegister.setSelectionColor(new java.awt.Color(102, 0, 102));
        jUsernameEnterRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameEnterRegisterActionPerformed(evt);
            }
        });

        jUsernameRegister.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jUsernameRegister.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameRegister.setText("Username");
        jUsernameRegister.setToolTipText("");

        jPasswordRegister.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPasswordRegister.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordRegister.setText("Password");
        jPasswordRegister.setToolTipText("");

        jPasswordEnterRegister.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPasswordEnterRegister.setSelectionColor(new java.awt.Color(102, 0, 102));
        jPasswordEnterRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordEnterRegisterActionPerformed(evt);
            }
        });

        jSubmit.setBackground(new java.awt.Color(255, 255, 255));
        jSubmit.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jSubmit.setForeground(new java.awt.Color(102, 0, 102));
        jSubmit.setText("Submit");
        jSubmit.setBorderPainted(false);
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });

        jBackRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/interface-arrows-turn-backward-3qynn3z1e3rizbfnn8xln.png"))); // NOI18N
        jBackRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackRegisterMouseClicked(evt);
            }
        });

        jExitRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/interface-delete-1-x8zqpdddl47ewg5ugtkv2.png"))); // NOI18N
        jExitRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegisterLayout = new javax.swing.GroupLayout(jPanelRegister);
        jPanelRegister.setLayout(jPanelRegisterLayout);
        jPanelRegisterLayout.setHorizontalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBackRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jExitRegister))
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUsernameRegister)
                            .addComponent(jNameRegister, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEmailRegister, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNumberRegister, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordRegister, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNameEnterRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordEnterRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUsernameEnterRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmailEnterRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNumberEnterRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 77, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelRegisterLayout.setVerticalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBackRegister)
                    .addComponent(jExitRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameEnterRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmailEnterRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmailRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumberEnterRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNumberRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameEnterRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsernameRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordEnterRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordRegister))
                .addGap(35, 35, 35)
                .addComponent(jSubmit)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
//        String name = jNameEnterRegister.getText();
//        String password = jPasswordEnterRegister.getText();
//        String email = jEmailEnterRegister.getText();
//        Integer number = Integer.parseInt(jNumberEnterRegister.getText());
//        String username = jUsernameEnterRegister.getText();
//        for (Node Customer = node.getUsername(); Customer!=null;) {
//        if (username = )
//            }
//    if(!(name.equals("") || password.equals("") || email.equals("") || username.equals(""))) {
        try {
            String name = jNameEnterRegister.getText();
            String password = jPasswordEnterRegister.getText();
            String email = jEmailEnterRegister.getText();
            Integer number = Integer.parseInt(jNumberEnterRegister.getText());
            String username = jUsernameEnterRegister.getText();
            
            if(!(name.equals("") || password.equals("") || email.equals("") || username.equals("") || number.toString().equals(""))) {
                Customer j = new Customer (username, password, name, email, number);
                j.submit();
                JOptionPane.showMessageDialog(this, "You registered successfully");
                new Login().setVisible(true);
                 } else { JOptionPane.showMessageDialog(this, "Please fill all of the fields to be able to register");}
        }
        catch  (Exception ex) {
            String name = jNameEnterRegister.getText();
            String password = jPasswordEnterRegister.getText();
            String email = jEmailEnterRegister.getText();
            String username = jUsernameEnterRegister.getText();
            if(jNumberEnterRegister.getText().equals("") || name.equals("") || password.equals("") || email.equals("") || username.equals("")) {
                JOptionPane.showMessageDialog(this, "Please fill all of the fields to be able to register");
             } else { JOptionPane.showMessageDialog(this, "Fill number field with ONLY numbers");}
        }
//    } else { JOptionPane.showMessageDialog(this, "Please fill all of the fields to be able to register");}
    
    }//GEN-LAST:event_jSubmitActionPerformed

    private void jPasswordEnterRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordEnterRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordEnterRegisterActionPerformed

    private void jNameEnterRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameEnterRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameEnterRegisterActionPerformed

    private void jUsernameEnterRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameEnterRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameEnterRegisterActionPerformed

    private void jEmailEnterRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailEnterRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailEnterRegisterActionPerformed

    private void jNumberEnterRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumberEnterRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumberEnterRegisterActionPerformed

    private void jExitRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitRegisterMouseClicked
        dispose();
        System.exit (0);
    }//GEN-LAST:event_jExitRegisterMouseClicked

    private void jBackRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackRegisterMouseClicked
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBackRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackRegister;
    private javax.swing.JTextField jEmailEnterRegister;
    private javax.swing.JLabel jEmailRegister;
    private javax.swing.JLabel jExitRegister;
    private javax.swing.JTextField jNameEnterRegister;
    private javax.swing.JLabel jNameRegister;
    private javax.swing.JTextField jNumberEnterRegister;
    private javax.swing.JLabel jNumberRegister;
    private javax.swing.JPanel jPanelRegister;
    private javax.swing.JPasswordField jPasswordEnterRegister;
    private javax.swing.JLabel jPasswordRegister;
    private javax.swing.JButton jSubmit;
    private javax.swing.JTextField jUsernameEnterRegister;
    private javax.swing.JLabel jUsernameRegister;
    // End of variables declaration//GEN-END:variables
}
